### ISSUE TITLE
Samples-Net provider examples do not build with ctrlx-datalayer 4.0.1

### ISSUE THREAD

**Issue by ArcherThompson** [boschrexroth/ctrlx-automation-sdk#52]
all .net provider example will not build 
The build error is 
/home/boschrexroth/ctrlx-automation-sdk/samples-net/datalayer.provider.alldata/Node.cs(231,28): error CS0012: The type 'NodeClass' is defined in an assembly that is not referenced. You must add a reference to assembly 'datalayer.fbs, Version=2.6.0.0, Culture=neutral, PublicKeyToken=e0e3d33bc06ef59b'. [/home/boschrexroth/ctrlx-automation-sdk/samples-net/datalayer.provider.alldata/datalayer.provider.alldata.csproj]

The package can be seen and decompiled at 
`#region Assembly datalayer.fbs, Version=2.6.0.0, Culture=neutral, PublicKeyToken=null
// /home/boschrexroth/.nuget/packages/ctrlx-datalayer.flatbuffers/2.6.0/lib/net8.0/datalayer.fbs.dll
// Decompiled with ICSharpCode.Decompiler 
#endregion

namespace comm.datalayer;

public enum NodeClass : sbyte
{
    Node,
    Method,
    Type,
    Variable,
    Collection,
    Resource,
    Program,
    Folder
}`

no amount of cleaning, restoring or other things like that help happens consistently on fresh builds and installs across multiple developers. 

note
The ctrlX-DataLayer.Flatbuffers package is being pulled in as a transitive dependency by ctrlX-DataLayer. 

Fresh projects seem to recreate the same issue

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
Thank you for using the ctrlX Datalayer .NET API.

- Please update and install latest SDK  [https://github.com/boschrexroth/ctrlx-automation-sdk/releases/tag/2.6.7]
- Ensure **ctrlX-Datalayer.4.0.1.nupkg** and **ctrlX-Datalayer.Flatbuffers.2.6.0.nupkg** in folder **./nuget** to be fetched as nuget sources.
- Navigate to your sample directory
- Clean your nuget cache by executing in terminal: **dotnet nuget locals all --clear**
- Execute: dotnet clean, dotnet restore, dotnet build
- Terminal -> Run Build task -> Build snap ...

If the issue should be still present, please reopen.

**Comment by ZmRZjFuDsDiR4qi5801F** [comment]
Please follow instructions to fix the issue.
